# Generated by Django 6.0.3 on 2026-04-05 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_category', models.CharField(choices=[('execution', 'Execution'), ('support', 'Support'), ('management', 'Management'), ('strategic', 'Strategic')], default='execution', max_length=20)),
                ('quantitative_weight', models.PositiveSmallIntegerField(default=40)),
                ('qualitative_weight', models.PositiveSmallIntegerField(default=30)),
                ('attendance_weight', models.PositiveSmallIntegerField(default=15)),
                ('self_weight', models.PositiveSmallIntegerField(default=10)),
                ('managerial_weight', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('execution', 'Execution'), ('support', 'Support'), ('management', 'Management'), ('strategic', 'Strategic')], default='execution', max_length=20)),
                ('hierarchy_level', models.PositiveSmallIntegerField(default=1)),
                ('is_quantitative', models.BooleanField(default=True)),
                ('is_managerial', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('hierarchy_level', 'title'),
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='organization.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='evaluation_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.evaluationprofile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.jobposition'),
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='sick', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('justified', models.BooleanField(default=True)),
                ('medical_certificate', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='organization.agent')),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('sick_leave', 'Sick leave')], default='present', max_length=20)),
                ('minutes_late', models.PositiveIntegerField(default=0)),
                ('remark', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organization.agent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('presence_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('sick_leave', 'Sick leave')], default='present', max_length=20)),
                ('quality_note', models.PositiveSmallIntegerField(default=3)),
                ('discipline_note', models.PositiveSmallIntegerField(default=3)),
                ('remark', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_followups', to='organization.agent')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
