# Generated by Django 6.0.3 on 2026-04-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_evaluationprofile_jobposition_agent_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('performance_weight', models.PositiveSmallIntegerField(default=50)),
                ('competency_weight', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='job_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.jobfamily'),
        ),
        migrations.AddField(
            model_name='evaluationprofile',
            name='job_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_profiles', to='organization.jobfamily'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='job_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='organization.jobfamily'),
        ),
    ]
