# Generated by Django 6.0.3 on 2026-04-18 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_notification_report_campaignassignment'),
        ('organization', '0003_jobfamily_agent_job_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_requests', to='organization.agent'),
        ),
        migrations.AddField(
            model_name='compliancerequest',
            name='manager_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compliancerequest',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
