# Generated by Codex on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0009_compliancerequest_assigned_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationcriterion",
            name="form_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criteria",
                to="evaluations.evaluationformversion",
            ),
        ),
        migrations.AddField(
            model_name="evaluationcriterion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
